{
 "title": "ITMO-553",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Alias By Disk Used ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.hosts.*.df-root.percent_bytes-used"
    }
   ]
  },
  {
   "title": "Riemanna  Collectd Process -cpu percent-system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.hosts.riemanna.cpu.percent-system"
    }
   ]
  },
  {
   "title": "Alias by Memory Used",
   "type": "graph",
   "description": "host1, Riemanna riemannmc\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(productiona.hosts.*.memory.memory-used, 2)"
    }
   ]
  },
  {
   "title": "Alias by Memory (used) all hosts",
   "type": "graph",
   "description": "Riemanna, Riemannmc, host1\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.*.*.memory.memory-used"
    }
   ]
  },
  {
   "title": "Group by CPU (user and system) for all hosts",
   "type": "graph",
   "description": "Riemanna, Riemannmc, Host1\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(productiona.hosts.*.cpu.{percent-user,percent-system}, 2, 'sumSeries')"
    }
   ]
  },
  {
   "title": "RiemannA, B, MC Streams Rate GraphiteMC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.hosts.*.riemann.streams.latency.5"
    }
   ]
  },
  {
   "title": "GraphiteMC Carbon Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "carbon.agents.*.cpuUsage" }
   ]
  }
 ]
}