{
 "title": "ProductionA -RiemannA, Host1",
 "description": "RiemanA  Host1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Alias by Disk Used Percent byte df-root GraphiteA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(productiona.hosts.*.df-root.percent_bytes-used, 2)"
    }
   ]
  },
  {
   "title": "Memory Disk Used all hosts GraphiteA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(productiona.hosts.*.memory.percent-used, 2)"
    }
   ]
  },
  {
   "title": "All Hosts collectd Process ps_data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.hosts.*.processes-collectd.ps_data"
    }
   ]
  },
  {
   "title": "Streams Rate Riemann A ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.hosts.riemanna.riemann.streams.rate"
    }
   ]
  },
  {
   "title": "Carbon CPU Usage GraphiteA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "carbon.agents.*.cpuUsage" }
   ]
  },
  {
   "title": "RIemann A Streams Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.hosts.riemanna.riemann.streams.rate"
    }
   ]
  },
  {
   "title": "Carbon Relay CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "carbon.relays.graphitea-1.cpuUsage"
    }
   ]
  }
 ]
}