{
 "title": "ProductionA - RiemannA, RiemannMC, Host1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage Stress Test Host1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.hosts.host1.cpu.percent-user"
    }
   ]
  },
  {
   "title": "Carbon Relay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "carbon.relays.graphitemc-1.cpuUsage"
    }
   ]
  },
  {
   "title": "Streams Rate RiemannA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.hosts.*.riemann.streams.rate"
    }
   ]
  },
  {
   "title": "Memory Used All Hosts ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.*.*.memory.memory-used"
    }
   ]
  },
  {
   "title": "Alias By Disk Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productiona.hosts.*.df-root.percent_bytes-used"
    }
   ]
  }
 ]
}